### ISSUE TITLE
[init] 프로젝트 초기 세팅 

### ISSUE THREAD

**Issue by emjayMJkim** [DGU-AITHON-BANSAMJO/camputhon-client#1]
## 🛠️ ISSUE
- 프로젝트 초기 세팅 

## 📑 To-Do
- [x] git ignore 설정
- [x] gradle 세팅 
- [x] app 기초세팅 및 폴더링 
- [x] 서버통신 기초 세팅 및 서버통신 테스트
